1. Write Python Programs to use various operators in Python

In [1]:
x = 10
y = 20

In [2]:
x+y

30

In [3]:
x-y

-10

In [4]:
x*y

200

In [5]:
x/y

0.5

In [6]:
x%y

10

In [7]:
x//y

0

In [8]:
x**y

100000000000000000000

2. Create list of elements and slice and dice it

In [9]:
List = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print("\nOriginal List:\n", List)
print("\nSliced Lists: ")
print(List[3:9:2])
print(List[::2])
print(List[::])


Original List:
 [1, 2, 3, 4, 5, 6, 7, 8, 9]

Sliced Lists: 
[4, 6, 8]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
import random
def dice():
    n = input( "Enter # of dice [3,6]: " )
    n = int( n )
    diceList = []
    for row in range(0, n):
        diceList.append(random.randint(1, 6))
    print( "\nYou have rolled: ", diceList)
dice()

Enter # of dice [3,6]: 4

You have rolled:  [1, 6, 2, 3]


4. Write a python program Read & write Excel files 

In [11]:
import pandas as pd
info = pd.DataFrame({'States':['California', 'Florida', 'Montana', 'Colorodo', 'Washington', 'Virginia'],
    'Capitals':['Sacramento', 'Tallahassee', 'Helena', 'Denver', 'Olympia', 'Richmond'],
    'Population':['508529', '193551', '32315', '619968', '52555', '227032']})

In [12]:
# writing excel file
info.to_excel('./info.xlsx')

In [13]:
info.to_excel('./info.xlsx', sheet_name='info', index=False)

In [19]:
from bs4 import BeautifulSoup
import urllib.request

In [20]:
url = 'https://www.yelp.com/biz/milk-and-cream-cereal-bar-new-york?osq=Ice+Cream'
ourUrl = urllib.request.urlopen(url)

In [21]:
soup = BeautifulSoup(ourUrl,'html.parser')

In [22]:
print(soup.prettify())

<!DOCTYPE HTML>
<!--[if lt IE 7 ]> <html xmlns:fb="http://www.facebook.com/2008/fbml" class="ie6 ie ltie9 ltie8 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html xmlns:fb="http://www.facebook.com/2008/fbml" class="ie7 ie ltie9 ltie8 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html xmlns:fb="http://www.facebook.com/2008/fbml" class="ie8 ie ltie9 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html xmlns:fb="http://www.facebook.com/2008/fbml" class="ie9 ie no-js" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="no-js" lang="en" xmlns:fb="http://www.facebook.com/2008/fbml">
 <!--<![endif]-->
 <head>
  <script nonce="a515cefc">
   (function() {
                var main = null;

                var main=function(){window.onerror=function(k,a,c,i,f){var j=(document.getElementsByTagName("html")[0].getAttribute("webdriver")==="true"||navigator.userAgent==="selenium");var h=f&&(f.name==="ServerSideRenderingError"||f.name==="CSRFallbackError");if(j&&!h){documen

In [23]:
review = []
for i in soup.find_all('div',{'class':'review-content'}):
  per_review=i.find('p')
  print(per_review)
  review.append(per_review)

In [24]:
len(review)

0

Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [25]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [26]:
import numpy as np
l = [1,2,3,4]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [1, 2, 3, 4]
One-dimensional NumPy array:  [1 2 3 4]


8. "Write a Python program to create a null vector of size 10 and update sixth value to 11

In [27]:
import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]
